name: travellio_round2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tv.png
    - assets/bulb.png
    - assets/lock.png
    - assets/thermometer.png
    - assets/lightbg.png
    - assets/tvbg.png
    - assets/lockbg.png
    - assets/ac.png
    - assets/acbg.png
